# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\varfolomey\Desktop\terver_lab2_task3\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.solveType = QtWidgets.QComboBox(self.centralwidget)
        self.solveType.setGeometry(QtCore.QRect(130, 50, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solveType.setFont(font)
        self.solveType.setObjectName("solveType")
        self.solveType.addItem("")
        self.solveType.addItem("")
        self.solveType.addItem("")
        self.amountLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountLabel.setGeometry(QtCore.QRect(130, 110, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amountLabel.setFont(font)
        self.amountLabel.setObjectName("amountLabel")
        self.amountSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.amountSpinBox.setGeometry(QtCore.QRect(350, 110, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amountSpinBox.setFont(font)
        self.amountSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.amountSpinBox.setObjectName("amountSpinBox")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(130, 150, 411, 201))
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.adviceLabel = QtWidgets.QLabel(self.centralwidget)
        self.adviceLabel.setGeometry(QtCore.QRect(130, 370, 421, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adviceLabel.setFont(font)
        self.adviceLabel.setObjectName("adviceLabel")
        self.numbersSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.numbersSpinBox.setGeometry(QtCore.QRect(140, 400, 401, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numbersSpinBox.setFont(font)
        self.numbersSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.numbersSpinBox.setObjectName("numbersSpinBox")
        self.resultLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLineEdit.setGeometry(QtCore.QRect(140, 470, 381, 22))
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.solveButton = QtWidgets.QPushButton(self.centralwidget)
        self.solveButton.setGeometry(QtCore.QRect(140, 510, 381, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solveButton.setFont(font)
        self.solveButton.setObjectName("solveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.solveType.setItemText(0, _translate("MainWindow", "Только k станков потребует наладки"))
        self.solveType.setItemText(1, _translate("MainWindow", "Хотя бы k станков потребют наладки"))
        self.solveType.setItemText(2, _translate("MainWindow", "Только заданные станки потребуют наладки"))
        self.amountLabel.setText(_translate("MainWindow", "Количество станков"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Вероятность"))
        self.adviceLabel.setText(_translate("MainWindow", "TextLabel"))
        self.solveButton.setText(_translate("MainWindow", "PushButton"))
